Watching for file changes with StatReloader
Cannot execute silk_profile as silk is not installed correctly.
Not Found: /
Watching for file changes with StatReloader
Cannot execute silk_profile as silk is not installed correctly.
Not Found: /favicon.ico
D:\Django\Blog\Blog\settings\common.py changed, reloading.
Watching for file changes with StatReloader
Cannot execute silk_profile as silk is not installed correctly.
D:\Django\Blog\Blog\settings\common.py changed, reloading.
Watching for file changes with StatReloader
Cannot execute silk_profile as silk is not installed correctly.
D:\Django\Blog\Blog\settings\common.py changed, reloading.
Watching for file changes with StatReloader
D:\Django\Blog\Blog\settings\common.py changed, reloading.
Watching for file changes with StatReloader
D:\Django\Blog\Blog\settings\common.py changed, reloading.
Watching for file changes with StatReloader
D:\Django\Blog\Blog\settings\common.py changed, reloading.
Watching for file changes with StatReloader
D:\Django\Blog\Blog\settings\common.py changed, reloading.
Watching for file changes with StatReloader
D:\Django\Blog\Blog\settings\common.py changed, reloading.
Watching for file changes with StatReloader
D:\Django\Blog\Blog\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Django\Blog\Blog\urls.py changed, reloading.
Watching for file changes with StatReloader
Cannot execute silk_profile as silk is not installed correctly.
D:\Django\Blog\Blog\settings\common.py changed, reloading.
Watching for file changes with StatReloader
Cannot execute silk_profile as silk is not installed correctly.
D:\Django\Blog\Blog\settings\common.py changed, reloading.
Watching for file changes with StatReloader
Cannot execute silk_profile as silk is not installed correctly.
D:\Django\Blog\Blog\urls.py changed, reloading.
Watching for file changes with StatReloader
Cannot execute silk_profile as silk is not installed correctly.
D:\Django\Blog\Blog\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Django\Blog\Blog\urls.py changed, reloading.
Watching for file changes with StatReloader
Cannot execute silk_profile as silk is not installed correctly.
D:\Django\Blog\Blog\settings\common.py changed, reloading.
Watching for file changes with StatReloader
Cannot execute silk_profile as silk is not installed correctly.
Watching for file changes with StatReloader
Cannot execute silk_profile as silk is not installed correctly.
Not Found: /media/author_avatars/IMG_20230210_162759_040_oR5kxYi.jpg
Not Found: /media/author_avatars/IMG_20230210_162759_040_oR5kxYi.jpg
Watching for file changes with StatReloader
Cannot execute silk_profile as silk is not installed correctly.
Internal Server Error: /api/posts/
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\fields.py", line 1870, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "D:\Django\Blog\weblog\serializers.py", line 41, in get_image_thumbnail
    return obj.get_image_url('thumbnail')
           ^^^^^^^^^^^^^^^^^
AttributeError: 'Post' object has no attribute 'get_image_url'
Internal Server Error: /api/posts/
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\fields.py", line 1870, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "D:\Django\Blog\weblog\serializers.py", line 41, in get_image_thumbnail
    return obj.get_image_url('thumbnail')
           ^^^^^^^^^^^^^^^^^
AttributeError: 'Post' object has no attribute 'get_image_url'
Not Found: /favicon.ico
Internal Server Error: /api/posts/
Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\.virtualenvs\Blog-urkGUUv0\Lib\site-packages\rest_framework\fields.py", line 1870, in to_representation
    return method(value)
           ^^^^^^^^^^^^^
  File "D:\Django\Blog\weblog\serializers.py", line 41, in get_image_thumbnail
    return obj.get_image_url('thumbnail')
           ^^^^^^^^^^^^^^^^^
AttributeError: 'Post' object has no attribute 'get_image_url'
D:\Django\Blog\weblog\serializers.py changed, reloading.
Watching for file changes with StatReloader
Cannot execute silk_profile as silk is not installed correctly.
Not Found: /media/author_avatars/IMG_20230210_162759_040_oR5kxYi.jpg
Watching for file changes with StatReloader
D:\Django\Blog\weblog\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Django\Blog\weblog\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Django\Blog\weblog\views.py changed, reloading.
Watching for file changes with StatReloader
Cannot execute silk_profile as silk is not installed correctly.
